dist: xenial
language: python
python: 3.6
env:
  matrix:
    - SELENIUM-WEBDRIVER=default
addons:
  postgresql: "9.6"
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - wget http://chromedriver.storage.googleapis.com/75.0.3770.90/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6/bin/
  - export CHROME_BIN=chromium-browser
script: 
  - python manage.py test
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: air-quality
  run: python manage.py migrate
  on: master
  