# Generated by Django 2.1.2 on 2019-01-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
