# Generated by Django 2.1.2 on 2019-02-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emissions', '0002_species_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('link', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='HealthAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='code',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='species',
            name='health_effect',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='species',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
