# Generated by Django 2.1.7 on 2019-02-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emissions', '0003_auto_20190214_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('code', models.CharField(default='', max_length=3)),
                ('site_type', models.TextField(default='')),
                ('local_auth', models.TextField(default='')),
                ('link', models.URLField(default='')),
                ('latitude', models.FloatField(default='')),
                ('longitude', models.FloatField(default='')),
                ('site_still_active', models.BooleanField(default=False)),
                ('site_date_open', models.DateTimeField(blank=True, null=True)),
                ('site_date_close', models.DateTimeField(blank=True, null=True)),
                ('co_measure_active', models.BooleanField(default=False)),
                ('no2_measure_active', models.BooleanField(default=False)),
                ('o3_measure_active', models.BooleanField(default=False)),
                ('pm10_measure_active', models.BooleanField(default=False)),
                ('pm25_measure_active', models.BooleanField(default=False)),
                ('so2_measure_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='healthadvice',
            name='advice_at_risk',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='healthadvice',
            name='advice_gen_pop',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='healthadvice',
            name='lower_index',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='healthadvice',
            name='quality_band',
            field=models.TextField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='healthadvice',
            name='upper_index',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
