# Generated by Django 2.1.7 on 2019-02-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emissions', '0004_auto_20190221_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site_date_close',
            new_name='site_date_closed',
        ),
    ]
