# Generated by Django 2.1.2 on 2019-05-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emissions', '0006_auto_20190221_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('code', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('link', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterField(
            model_name='site',
            name='local_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emissions.LocalAuthority'),
        ),
    ]
